image: node:22

# Steg i vår pipeline
stages:
  - validate
  - build
  - deploy

# Cacha node_modules mellan jobb och körningar för snabbare pipelines
cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

# Förinställning för alla Node-jobb
.node_template:
  before_script:
    - npm ci --cache .npm --prefere-offline

# --- STAGE: VALIDATE ---

security_audit:
  extends: .node_template
  stage: validate
  script:
    - npm audit --audit-level=high

lint_and_typecheck:
  extends: .node_template
  stage: validate
  script:
    - npm run lint
    - npx tsc -b

unit_tests:
  extends: .node_template
  stage: validate
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 30 days

# --- STAGE: BUILD ---

build:
  extends: .node_template
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

# --- STAGE: DEPLOY ---

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - cp -r dist public # Eller motsvarande din build-mapp ( t.ex. build/ eller output/ )
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
